services:
  - type: web
    name: hackernews-ai-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.routes:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HACKERNEWS_API_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 