services:
  - type: web
    name: hackernews-ai-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HACKERNEWS_API_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 